/* soapStub.h
   Generated by gSOAP 2.8.8 from syCwmp.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#ifndef SY_CWMP_H
#define SY_CWMP_H
#endif //SY_CWMP_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20808
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (12)
/* xsd:boolean */
enum xsd__boolean {false_ = 0, true_ = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParaAttrStruct_Notification
#define SOAP_TYPE__cwmp__SetParaAttrStruct_Notification (13)
/* cwmp:SetParaAttrStruct-Notification */
enum _cwmp__SetParaAttrStruct_Notification {_cwmp__SetParaAttrStruct_Notification__0 = 0, _cwmp__SetParaAttrStruct_Notification__1 = 1, _cwmp__SetParaAttrStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp__SetParaValRes_Status
#define SOAP_TYPE__cwmp__SetParaValRes_Status (14)
/* cwmp:SetParaValRes-Status */
enum _cwmp__SetParaValRes_Status {_cwmp__SetParaValRes_Status__0 = 0, _cwmp__SetParaValRes_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__SetParaAttrStructRes_Notification
#define SOAP_TYPE__cwmp__SetParaAttrStructRes_Notification (15)
/* cwmp:SetParaAttrStructRes-Notification */
enum _cwmp__SetParaAttrStructRes_Notification {_cwmp__SetParaAttrStructRes_Status__0 = 0, _cwmp__SetParaAttrStructRes_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__AddObjRes_Status
#define SOAP_TYPE__cwmp__AddObjRes_Status (16)
/* cwmp:AddObjRes-Status */
enum _cwmp__AddObjRes_Status {_cwmp__AddObjRes_Status__0 = 0, _cwmp__AddObjRes_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DelObjRes_Status
#define SOAP_TYPE__cwmp__DelObjRes_Status (17)
/* cwmp:DelObjRes-Status */
enum _cwmp__DelObjRes_Status {_cwmp__DelObjRes_Status__0 = 0, _cwmp__DelObjRes_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__DownloadRes_Status
#define SOAP_TYPE__cwmp__DownloadRes_Status (18)
/* cwmp:DownloadRes-Status */
enum _cwmp__DownloadRes_Status {_cwmp__DownloadRes_Status__0 = 0, _cwmp__DownloadRes_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp__UploadRes_Status
#define SOAP_TYPE__cwmp__UploadRes_Status (19)
/* cwmp:UploadRes-Status */
enum _cwmp__UploadRes_Status {_cwmp__UploadRes_Status__0 = 0, _cwmp__UploadRes_Status__1 = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_cwmp__FaultStruct
#define SOAP_TYPE_cwmp__FaultStruct (20)
/* cwmp:FaultStruct */
struct cwmp__FaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (21)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	char *cwmp__ID;	/* mustUnderstand */
};
#endif

#ifndef SOAP_TYPE_cwmp__MethodList
#define SOAP_TYPE_cwmp__MethodList (22)
/* cwmp:MethodList */
struct cwmp__MethodList
{
	int __size;	/* sequence of elements <string> */
	char **__ptrstring;
};
#endif

#ifndef SOAP_TYPE_cwmp__GetRPCMethodsResponse
#define SOAP_TYPE_cwmp__GetRPCMethodsResponse (24)
/* cwmp:GetRPCMethodsResponse */
struct cwmp__GetRPCMethodsResponse
{
	struct cwmp__MethodList __ptrMethodList;	/* SOAP 1.2 RPC return element (when namespace qualified) */
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterValueStruct
#define SOAP_TYPE_cwmp__ParameterValueStruct (25)
/* cwmp:ParameterValueStruct */
typedef
struct cwmp__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
	char *Type;	/* required element of type xsd:string */
} cwmp_PVS_t;
#endif

#ifndef SOAP_TYPE_ParameterValueList
#define SOAP_TYPE_ParameterValueList (26)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
typedef
struct ParameterValueList
{
	struct cwmp__ParameterValueStruct **__ptrParameterValueStruct;
	#define ptrPVS __ptrParameterValueStruct
	int __size;
} PVL_t;
#endif

#ifndef SOAP_TYPE_ParameterNames
#define SOAP_TYPE_ParameterNames (29)
/* SOAP encoded array of xsd:string schema type: */
struct ParameterNames
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_AccessList
#define SOAP_TYPE_AccessList (30)
/* SOAP encoded array of xsd:string schema type: */
struct AccessList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp__SetParameterAttributesStruct (31)
/* cwmp:SetParameterAttributesStruct */
struct cwmp__SetParameterAttributesStruct
{
	char **Name;	/* optional element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum _cwmp__SetParaAttrStruct_Notification Notification;	/* required element of type cwmp:SetParaAttrStruct-Notification */
	char *AccessListChange;	/* required element of type xsd:string */
	struct AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_SetParameterAttributesList
#define SOAP_TYPE_SetParameterAttributesList (33)
/* SOAP encoded array of cwmp:SetParameterAttributesStruct schema type: */
struct SetParameterAttributesList
{
	struct cwmp__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__EventStruct
#define SOAP_TYPE_cwmp__EventStruct (36)
/* cwmp:EventStruct */
struct cwmp__EventStruct
{
	char *EventCode;	/* required element of type xsd:string */
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterValuesResponse
#define SOAP_TYPE_cwmp__GetParameterValuesResponse (37)
/* cwmp:GetParameterValuesResponse */
struct cwmp__GetParameterValuesResponse
{
	struct ParameterValueList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterValuesResponse
#define SOAP_TYPE_cwmp__SetParameterValuesResponse (39)
/* cwmp:SetParameterValuesResponse */
struct cwmp__SetParameterValuesResponse
{
	enum _cwmp__SetParaValRes_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:SetParaValRes-Status */
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterNamesResponse
#define SOAP_TYPE_cwmp__GetParameterNamesResponse (40)
/* cwmp:GetParameterNamesResponse */
struct cwmp__GetParameterNamesResponse
{
	struct ParameterInfoList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE_ParameterInfoList
#define SOAP_TYPE_ParameterInfoList (41)
/* SOAP encoded array of cwmp:ParameterInfoStruct schema type: */
typedef
struct ParameterInfoList
{
	struct cwmp__ParameterInfoStruct **__ptrParameterInfoStruct;
	#define ptrPIS __ptrParameterInfoStruct
	int __size;
} PIL_t;
#endif

#ifndef SOAP_TYPE_cwmp__ParameterInfoStruct
#define SOAP_TYPE_cwmp__ParameterInfoStruct (43)
/* cwmp:ParameterInfoStruct */
typedef
struct cwmp__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	int Writable;	/* required element of type xsd:int */
} cwmp_PIS_t;
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributesResponse
#define SOAP_TYPE_cwmp__SetParameterAttributesResponse (46)
/* cwmp:SetParameterAttributesResponse */
struct cwmp__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterAttributesResponse
#define SOAP_TYPE_cwmp__GetParameterAttributesResponse (47)
/* cwmp:GetParameterAttributesResponse */
struct cwmp__GetParameterAttributesResponse
{
	struct ParameterAttributeList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE_ParameterAttributeList
#define SOAP_TYPE_ParameterAttributeList (48)
/* SOAP encoded array of cwmp:ParameterAttributeStruct schema type: */
struct ParameterAttributeList
{
	struct cwmp__ParameterAttributeStruct **__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__ParameterAttributeStruct
#define SOAP_TYPE_cwmp__ParameterAttributeStruct (50)
/* cwmp:ParameterAttributeStruct */
struct cwmp__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum _cwmp__SetParaAttrStructRes_Notification Notification;	/* required element of type cwmp:SetParaAttrStructRes-Notification */
	struct AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__AddObjectResponse
#define SOAP_TYPE_cwmp__AddObjectResponse (53)
/* cwmp:AddObjectResponse */
struct cwmp__AddObjectResponse
{
	unsigned int InstanceNumber;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
	enum _cwmp__AddObjRes_Status Status;	/* required element of type cwmp:AddObjRes-Status */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeleteObjectResponse
#define SOAP_TYPE_cwmp__DeleteObjectResponse (55)
/* cwmp:DeleteObjectResponse */
struct cwmp__DeleteObjectResponse
{
	enum _cwmp__DelObjRes_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:DelObjRes-Status */
};
#endif

#ifndef SOAP_TYPE_cwmp__DownloadResponse
#define SOAP_TYPE_cwmp__DownloadResponse (56)
/* cwmp:DownloadResponse */
struct cwmp__DownloadResponse
{
	enum _cwmp__DownloadRes_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:DownloadRes-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_cwmp__UploadResponse
#define SOAP_TYPE_cwmp__UploadResponse (58)
/* cwmp:UploadResponse */
struct cwmp__UploadResponse
{
	enum _cwmp__UploadRes_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp:UploadRes-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_cwmp__FactoryResetResponse
#define SOAP_TYPE_cwmp__FactoryResetResponse (59)
/* cwmp:FactoryResetResponse */
struct cwmp__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmp__ScheduleInformResponse
#define SOAP_TYPE_cwmp__ScheduleInformResponse (60)
/* cwmp:ScheduleInformResponse */
struct cwmp__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmp__TransferCompleteResponse
#define SOAP_TYPE_cwmp__TransferCompleteResponse (61)
/* cwmp:TransferCompleteResponse */
struct cwmp__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmp__RebootResponse
#define SOAP_TYPE_cwmp__RebootResponse (62)
/* cwmp:RebootResponse */
struct cwmp__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferComplete
#define SOAP_TYPE__cwmp__TransferComplete (63)
/* cwmp:TransferComplete */
struct _cwmp__TransferComplete
{
	char *CommandKey;	/* required element of type cwmp:CommandKeyType */
	struct cwmp__FaultStruct *FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp__TransferCompleteResponse
#define SOAP_TYPE__cwmp__TransferCompleteResponse (65)
/* cwmp:TransferCompleteResponse */
struct _cwmp__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp__Fault_SetParameterValuesFault (66)
/* cwmp:Fault-SetParameterValuesFault */
struct _cwmp__Fault_SetParameterValuesFault
{
	char *ParameterName;	/* required element of type xsd:string */
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp__Fault
#define SOAP_TYPE__cwmp__Fault (67)
/* cwmp:Fault */
struct _cwmp__Fault
{
	char *FaultCode;	/* required element of type cwmp:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
	int __sizeSetParameterValuesFault;	/* sequence of elements <SetParameterValuesFault> */
	struct _cwmp__Fault_SetParameterValuesFault *SetParameterValuesFault;	/* optional element of type cwmp:Fault-SetParameterValuesFault */
};
#endif

#ifndef SOAP_TYPE__DeviceIdStruct
#define SOAP_TYPE__DeviceIdStruct (69)
/* DeviceIdStruct */
struct _DeviceIdStruct
{
	char *Manufacturer;	/* optional element of type xsd:string */
	char *OUI;	/* optional element of type xsd:string */
	char *ProductClass;	/* optional element of type xsd:string */
	char *SerialNumber;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__EventStruct
#define SOAP_TYPE__EventStruct (70)
/* SOAP encoded array of cwmp:EventStruct schema type: */
struct _EventStruct
{
	struct cwmp__EventStruct *__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE__ParameterValueStruct
#define SOAP_TYPE__ParameterValueStruct (72)
/* SOAP encoded array of cwmp:ParameterValueStruct schema type: */
struct _ParameterValueStruct
{
	struct cwmp__ParameterValueStruct *__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp__InformResponse
#define SOAP_TYPE_cwmp__InformResponse (73)
/* cwmp:InformResponse */
struct cwmp__InformResponse
{
	unsigned int MaxEnvelopes;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE_cwmp__Inform
#define SOAP_TYPE_cwmp__Inform (79)
/* cwmp:Inform */
struct cwmp__Inform
{
	struct _DeviceIdStruct *DeviceId;	/* optional element of type DeviceIdStruct */
	struct _EventStruct *Event;	/* optional element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	char *CurrentTime;	/* optional element of type xsd:string */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct _ParameterValueStruct *ParameterList;	/* optional element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE_cwmp__GetRPCMethods
#define SOAP_TYPE_cwmp__GetRPCMethods (84)
/* cwmp:GetRPCMethods */
struct cwmp__GetRPCMethods
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterValues
#define SOAP_TYPE_cwmp__GetParameterValues (88)
/* cwmp:GetParameterValues */
struct cwmp__GetParameterValues
{
	struct ParameterNames *ParameterNames;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterValues
#define SOAP_TYPE_cwmp__SetParameterValues (91)
/* cwmp:SetParameterValues */
struct cwmp__SetParameterValues
{
	struct ParameterValueList *ParameterList;	/* optional element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* optional element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterNames
#define SOAP_TYPE_cwmp__GetParameterNames (94)
/* cwmp:GetParameterNames */
struct cwmp__GetParameterNames
{
	char **ParameterPath;	/* optional element of type xsd:string */
	char *NextLevel;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__SetParameterAttributes
#define SOAP_TYPE_cwmp__SetParameterAttributes (98)
/* cwmp:SetParameterAttributes */
struct cwmp__SetParameterAttributes
{
	struct SetParameterAttributesList *ParameterList;	/* optional element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE_cwmp__GetParameterAttributes
#define SOAP_TYPE_cwmp__GetParameterAttributes (101)
/* cwmp:GetParameterAttributes */
struct cwmp__GetParameterAttributes
{
	struct ParameterNames *ParameterNames;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp__AddObject
#define SOAP_TYPE_cwmp__AddObject (104)
/* cwmp:AddObject */
struct cwmp__AddObject
{
	char *ObjectName;	/* optional element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* optional element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__AddObjectIPTV
#define SOAP_TYPE_cwmp__AddObjectIPTV (106)
/* cwmp:AddObjectIPTV */
struct cwmp__AddObjectIPTV
{
	char *ObjectName;	/* optional element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* optional element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__DeleteObject
#define SOAP_TYPE_cwmp__DeleteObject (109)
/* cwmp:DeleteObject */
struct cwmp__DeleteObject
{
	char *ObjectName;	/* optional element of type cwmp:ObjectNameType */
	char *ParameterKey;	/* optional element of type cwmp:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__Reboot
#define SOAP_TYPE_cwmp__Reboot (112)
/* cwmp:Reboot */
struct cwmp__Reboot
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__Download
#define SOAP_TYPE_cwmp__Download (115)
/* cwmp:Download */
struct cwmp__Download
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
	char *FileType;	/* optional element of type xsd:string */
	char *URL;	/* optional element of type xsd:string */
	char *Username;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	int FileSize;	/* required element of type xsd:int */
	char *TargetFileName;	/* optional element of type xsd:string */
	int DelaySeconds;	/* required element of type xsd:int */
	char *SuccessURL;	/* optional element of type xsd:string */
	char *FailureURL;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp__Upload
#define SOAP_TYPE_cwmp__Upload (118)
/* cwmp:Upload */
struct cwmp__Upload
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
	char *FileType;	/* optional element of type xsd:string */
	char *URL;	/* optional element of type xsd:string */
	char *Username;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	int DelaySeconds;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_cwmp__FactoryReset
#define SOAP_TYPE_cwmp__FactoryReset (121)
/* cwmp:FactoryReset */
struct cwmp__FactoryReset
{
	void *_;	/* transient */
};
#endif

#ifndef SOAP_TYPE_cwmp__ScheduleInform
#define SOAP_TYPE_cwmp__ScheduleInform (124)
/* cwmp:ScheduleInform */
struct cwmp__ScheduleInform
{
	int DelaySeconds;	/* required element of type xsd:int */
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp__TransferComplete
#define SOAP_TYPE_cwmp__TransferComplete (127)
/* cwmp:TransferComplete */
struct cwmp__TransferComplete
{
	char *CommandKey;	/* optional element of type cwmp:CommandKeyType */
	struct cwmp__FaultStruct FaultStruct;	/* required element of type cwmp:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (128)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (130)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (131)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (132)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif



/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
typedef char *xsd__string;
#endif

#ifndef SOAP_TYPE_cwmp__ParameterKeyType
#define SOAP_TYPE_cwmp__ParameterKeyType (8)
typedef char *cwmp__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__ObjectNameType
#define SOAP_TYPE_cwmp__ObjectNameType (9)
typedef char *cwmp__ObjectNameType;
#endif

#ifndef SOAP_TYPE_cwmp__CommandKeyType
#define SOAP_TYPE_cwmp__CommandKeyType (10)
typedef char *cwmp__CommandKeyType;
#endif

#ifndef SOAP_TYPE_cwmp__FaultCodeType
#define SOAP_TYPE_cwmp__FaultCodeType (11)
typedef char *cwmp__FaultCodeType;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __Inform(struct soap*, struct _DeviceIdStruct *DeviceId, struct _EventStruct *Event, unsigned int MaxEnvelopes, char *CurrentTime, unsigned int RetryCount, struct _ParameterValueStruct *ParameterList, struct cwmp__InformResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 __GetRPCMethods(struct soap*, void *_, struct cwmp__GetRPCMethodsResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 __GetParaValues(struct soap*, struct ParameterNames *ParameterNames, struct cwmp__GetParameterValuesResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 __SetParaValues(struct soap*, struct ParameterValueList *ParameterList, char *ParameterKey, struct cwmp__SetParameterValuesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 __GetParaNames(struct soap*, char **ParameterPath, char *NextLevel, struct cwmp__GetParameterNamesResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 __SetParaAttr(struct soap*, struct SetParameterAttributesList *ParameterList, struct cwmp__SetParameterAttributesResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 __GetParaAttr(struct soap*, struct ParameterNames *ParameterNames, struct cwmp__GetParameterAttributesResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 __AddObject(struct soap*, char *ObjectName, char *ParameterKey, struct cwmp__AddObjectResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 __AddObjectIPTV(struct soap*, char *ObjectName, char *ParameterKey, struct cwmp__AddObjectResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 __DeleteObject(struct soap*, char *ObjectName, char *ParameterKey, struct cwmp__DeleteObjectResponse *_param_10);

SOAP_FMAC5 int SOAP_FMAC6 __Reboot(struct soap*, char *CommandKey, struct cwmp__RebootResponse *_param_11);

SOAP_FMAC5 int SOAP_FMAC6 __Download(struct soap*, char *CommandKey, char *FileType, char *URL, char *Username, char *Password, int FileSize, char *TargetFileName, int DelaySeconds, char *SuccessURL, char *FailureURL, struct cwmp__DownloadResponse *_param_12);

SOAP_FMAC5 int SOAP_FMAC6 __Upload(struct soap*, char *CommandKey, char *FileType, char *URL, char *Username, char *Password, int DelaySeconds, struct cwmp__UploadResponse *_param_13);

SOAP_FMAC5 int SOAP_FMAC6 __FactoryReset(struct soap*, void *_, struct cwmp__FactoryResetResponse *_param_14);

SOAP_FMAC5 int SOAP_FMAC6 __ScheduleInform(struct soap*, int DelaySeconds, char *CommandKey, struct cwmp__ScheduleInformResponse *_param_15);

SOAP_FMAC5 int SOAP_FMAC6 __TransferComplete(struct soap*, char *CommandKey, struct cwmp__FaultStruct FaultStruct, time_t StartTime, time_t CompleteTime, struct cwmp__TransferCompleteResponse *_param_16);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Inform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetRPCMethods(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__AddObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__AddObjectIPTV(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__DeleteObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Reboot(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Download(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Upload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__FactoryReset(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__ScheduleInform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__TransferComplete(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _DeviceIdStruct *DeviceId, struct _EventStruct *Event, unsigned int MaxEnvelopes, char *CurrentTime, unsigned int RetryCount, struct _ParameterValueStruct *ParameterList, struct cwmp__InformResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct cwmp__GetRPCMethodsResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ParameterNames *ParameterNames, struct cwmp__GetParameterValuesResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ParameterValueList *ParameterList, char *ParameterKey, struct cwmp__SetParameterValuesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, char **ParameterPath, char *NextLevel, struct cwmp__GetParameterNamesResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct SetParameterAttributesList *ParameterList, struct cwmp__SetParameterAttributesResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ParameterNames *ParameterNames, struct cwmp__GetParameterAttributesResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ObjectName, char *ParameterKey, struct cwmp__AddObjectResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__AddObjectIPTV(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ObjectName, char *ParameterKey, struct cwmp__AddObjectResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *ObjectName, char *ParameterKey, struct cwmp__DeleteObjectResponse *_param_10);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, struct cwmp__RebootResponse *_param_11);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, char *FileType, char *URL, char *Username, char *Password, int FileSize, char *TargetFileName, int DelaySeconds, char *SuccessURL, char *FailureURL, struct cwmp__DownloadResponse *_param_12);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, char *FileType, char *URL, char *Username, char *Password, int DelaySeconds, struct cwmp__UploadResponse *_param_13);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, void *_, struct cwmp__FactoryResetResponse *_param_14);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, int DelaySeconds, char *CommandKey, struct cwmp__ScheduleInformResponse *_param_15);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_cwmp__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *CommandKey, struct cwmp__FaultStruct FaultStruct, time_t StartTime, time_t CompleteTime, struct cwmp__TransferCompleteResponse *_param_16);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
