/* soapServer.c
   Generated by gSOAP 2.8.8 from syCwmp.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#include "syCwmpFault.h"
#include "syCwmpCommon.h"
#include "syCwmpSocket.h"
#include "syCwmpManagement.h"

extern syGlobalParmStruct gsyGlobalParmStru;
extern syAcsCpeParamStruct  gsyAcsCpeParamStru;


#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.8 2012-12-05 06:27:30 GMT")
void useless(){}
SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
    SOAP_DPrint("[%s] --->\n", __FUNCTION__);//linjieling
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#if 0 //linjieling
#ifndef WITH_FASTCGI
        if (soap->max_keep_alive > 0 && !--k)
            soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{
	        SOAP_DPrint("[%s] 1\n", __FUNCTION__);//linjieling
		    if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
            SOAP_DPrint("[%s] 2\n", __FUNCTION__);//linjieling
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
	        SOAP_DPrint("[%s] 3\n", __FUNCTION__);//linjieling
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
        SOAP_DPrint("[%s] 4\n", __FUNCTION__);//linjieling
#else  
        soap_begin(soap);
#ifndef WITH_FASTCGI
        SOAP_DPrint("[%s] max_keep_alive:%d, keep_alive:%d, k:%d\n", __FUNCTION__, 
            soap->max_keep_alive, soap->keep_alive, k);//linjieling
        if (soap->max_keep_alive > 0 && !--k)
            soap->keep_alive = 0;
#endif
        SOAP_DPrint("[%s] 1\n", __FUNCTION__);//linjieling
		if (soap_begin_recv(soap))
		{
	        SOAP_DPrint("[%s] soap->error:%d\n", __FUNCTION__, soap->error);//linjieling
		    if (soap->error < SOAP_STOP){
#ifdef WITH_FASTCGI
        		soap_send_fault(soap);
#else
        		return soap_send_fault(soap);
#endif
            }
            SOAP_DPrint("[%s] 2\n", __FUNCTION__);//linjieling
            soap_closesock(soap);
            SOAP_DPrint("[%s] 3\n", __FUNCTION__);//linjieling
            SOAP_DPrint("[%s] keep_alive:%d\n", __FUNCTION__, soap->keep_alive);//linjieling
            continue;
		}
        SOAP_DPrint("[%s] 4\n", __FUNCTION__);//linjieling
		if (soap_envelope_begin_in(soap)
                || soap_recv_header(soap)
                || soap_serve_request(soap) 
                || (soap->fserveloop && soap->fserveloop(soap)))
		{
	        printf("[%s] 5\n", __FUNCTION__);//linjieling
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}
        SOAP_DPrint("[%s] 6\n", __FUNCTION__);//linjieling
#endif
#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
        SOAP_DPrint("[%s] 7\n", __FUNCTION__);//linjieling
	} while (1);
#else
        SOAP_DPrint("[%s] 8\n", __FUNCTION__);//linjieling
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
    //SOAP_DPrint("[%s] --->\n", __FUNCTION__);//linjieling
	soap_peek_element(soap);
    SOAP_DPrint("[%s] tag:%s\n", __FUNCTION__, soap->tag);//linjieling
	DPrint("[%s] tag:%s\n", __FUNCTION__, soap->tag);

	if (!soap_match_tag(soap, soap->tag, "cwmp:Inform"))
		return soap_serve_cwmp__Inform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetRPCMethods"))
		return soap_serve_cwmp__GetRPCMethods(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterValues"))
		return soap_serve_cwmp__GetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterValues"))
		return soap_serve_cwmp__SetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterNames"))
		return soap_serve_cwmp__GetParameterNames(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:SetParameterAttributes"))
		return soap_serve_cwmp__SetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:GetParameterAttributes"))
		return soap_serve_cwmp__GetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:AddObject"))
		return soap_serve_cwmp__AddObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:AddObjectIPTV"))
		return soap_serve_cwmp__AddObjectIPTV(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:DeleteObject"))
		return soap_serve_cwmp__DeleteObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Reboot"))
		return soap_serve_cwmp__Reboot(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Download"))
		return soap_serve_cwmp__Download(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:Upload"))
		return soap_serve_cwmp__Upload(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:FactoryReset"))
		return soap_serve_cwmp__FactoryReset(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:ScheduleInform"))
		return soap_serve_cwmp__ScheduleInform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp:TransferComplete"))
		return soap_serve_cwmp__TransferComplete(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Inform(struct soap *soap)
{	struct cwmp__Inform soap_tmp_cwmp__Inform;
	struct cwmp__InformResponse _param_1;
	soap_default_cwmp__InformResponse(soap, &_param_1);
	soap_default_cwmp__Inform(soap, &soap_tmp_cwmp__Inform);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Inform(soap, &soap_tmp_cwmp__Inform, "cwmp:Inform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __Inform(soap, soap_tmp_cwmp__Inform.DeviceId, soap_tmp_cwmp__Inform.Event, soap_tmp_cwmp__Inform.MaxEnvelopes, soap_tmp_cwmp__Inform.CurrentTime, soap_tmp_cwmp__Inform.RetryCount, soap_tmp_cwmp__Inform.ParameterList, &_param_1);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__InformResponse(soap, &_param_1);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__InformResponse(soap, &_param_1, "cwmp:InformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__InformResponse(soap, &_param_1, "cwmp:InformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetRPCMethods(struct soap *soap)
{	struct cwmp__GetRPCMethods soap_tmp_cwmp__GetRPCMethods;
	struct cwmp__GetRPCMethodsResponse _param_2;
    SOAP_DPrint("[%s] --->\n", __FUNCTION__);//linjieling
	soap_default_cwmp__GetRPCMethodsResponse(soap, &_param_2);
	soap_default_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods);
	soap->encodingStyle = "";
    SOAP_DPrint("[%s] 1\n", __FUNCTION__);//linjieling
	if (!soap_get_cwmp__GetRPCMethods(soap, &soap_tmp_cwmp__GetRPCMethods, "cwmp:GetRPCMethods", NULL))
		return soap->error;
    SOAP_DPrint("[%s] 2\n", __FUNCTION__);//linjieling
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
    SOAP_DPrint("[%s] 3\n", __FUNCTION__);//linjieling
	soap->error = __GetRPCMethods(soap, soap_tmp_cwmp__GetRPCMethods._, &_param_2);
	if (soap->error)
		return soap->error;
    SOAP_DPrint("[%s] 4\n", __FUNCTION__);//linjieling
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetRPCMethodsResponse(soap, &_param_2);
	if (soap_begin_count(soap))
		return soap->error;
    SOAP_DPrint("[%s] 5\n", __FUNCTION__);//linjieling
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetRPCMethodsResponse(soap, &_param_2, "cwmp:GetRPCMethodsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
    SOAP_DPrint("[%s] 6\n", __FUNCTION__);//linjieling
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
	 //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetRPCMethodsResponse(soap, &_param_2, "cwmp:GetRPCMethodsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
    SOAP_DPrint("[%s] 7\n", __FUNCTION__);//linjieling
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterValues(struct soap *soap)
{	struct cwmp__GetParameterValues soap_tmp_cwmp__GetParameterValues;
	struct cwmp__GetParameterValuesResponse _param_3;
	soap_default_cwmp__GetParameterValuesResponse(soap, &_param_3);
	soap_default_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__GetParameterValues(soap, &soap_tmp_cwmp__GetParameterValues, "cwmp:GetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __GetParaValues(soap, soap_tmp_cwmp__GetParameterValues.ParameterNames, &_param_3);
 	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
#if 1
    int i;
    int size = 0;
    struct cwmp__ParameterValueStruct* paraValStruct = NULL;

    size = _param_3.ParameterList->__size;
    SOAP_DPrint("[%s] size=%d\n", __FUNCTION__, size);
    for(i = 0; i < size; i++){
        paraValStruct = _param_3.ParameterList->__ptrParameterValueStruct[i];
        SOAP_DPrint("[%s] element%d : name=%s, type=%s, value=%s\n", __FUNCTION__, i, 
            paraValStruct->Name,
            paraValStruct->Type,
            paraValStruct->Value);
    }
#endif
	soap_serialize_cwmp__GetParameterValuesResponse(soap, &_param_3);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterValuesResponse(soap, &_param_3, "cwmp:GetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterValuesResponse(soap, &_param_3, "cwmp:GetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterValues(struct soap *soap)
{	struct cwmp__SetParameterValues soap_tmp_cwmp__SetParameterValues;
	struct cwmp__SetParameterValuesResponse _param_4;
	soap_default_cwmp__SetParameterValuesResponse(soap, &_param_4);
	soap_default_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__SetParameterValues(soap, &soap_tmp_cwmp__SetParameterValues, "cwmp:SetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __SetParaValues(soap, soap_tmp_cwmp__SetParameterValues.ParameterList, soap_tmp_cwmp__SetParameterValues.ParameterKey, &_param_4);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__SetParameterValuesResponse(soap, &_param_4);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__SetParameterValuesResponse(soap, &_param_4, "cwmp:SetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__SetParameterValuesResponse(soap, &_param_4, "cwmp:SetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterNames(struct soap *soap)
{	struct cwmp__GetParameterNames soap_tmp_cwmp__GetParameterNames;
	struct cwmp__GetParameterNamesResponse _param_5;
	soap_default_cwmp__GetParameterNamesResponse(soap, &_param_5);
	soap_default_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__GetParameterNames(soap, &soap_tmp_cwmp__GetParameterNames, "cwmp:GetParameterNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __GetParaNames(soap, soap_tmp_cwmp__GetParameterNames.ParameterPath, soap_tmp_cwmp__GetParameterNames.NextLevel, &_param_5);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterNamesResponse(soap, &_param_5);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterNamesResponse(soap, &_param_5, "cwmp:GetParameterNamesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterNamesResponse(soap, &_param_5, "cwmp:GetParameterNamesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__SetParameterAttributes(struct soap *soap)
{	struct cwmp__SetParameterAttributes soap_tmp_cwmp__SetParameterAttributes;
	struct cwmp__SetParameterAttributesResponse _param_6;
	soap_default_cwmp__SetParameterAttributesResponse(soap, &_param_6);
	soap_default_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__SetParameterAttributes(soap, &soap_tmp_cwmp__SetParameterAttributes, "cwmp:SetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __SetParaAttr(soap, soap_tmp_cwmp__SetParameterAttributes.ParameterList, &_param_6);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__SetParameterAttributesResponse(soap, &_param_6);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__SetParameterAttributesResponse(soap, &_param_6, "cwmp:SetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__SetParameterAttributesResponse(soap, &_param_6, "cwmp:SetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__GetParameterAttributes(struct soap *soap)
{	struct cwmp__GetParameterAttributes soap_tmp_cwmp__GetParameterAttributes;
	struct cwmp__GetParameterAttributesResponse _param_7;
	soap_default_cwmp__GetParameterAttributesResponse(soap, &_param_7);
	soap_default_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__GetParameterAttributes(soap, &soap_tmp_cwmp__GetParameterAttributes, "cwmp:GetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __GetParaAttr(soap, soap_tmp_cwmp__GetParameterAttributes.ParameterNames, &_param_7);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__GetParameterAttributesResponse(soap, &_param_7);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__GetParameterAttributesResponse(soap, &_param_7, "cwmp:GetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__GetParameterAttributesResponse(soap, &_param_7, "cwmp:GetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__AddObject(struct soap *soap)
{	struct cwmp__AddObject soap_tmp_cwmp__AddObject;
	struct cwmp__AddObjectResponse _param_8;
	soap_default_cwmp__AddObjectResponse(soap, &_param_8);
	soap_default_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__AddObject(soap, &soap_tmp_cwmp__AddObject, "cwmp:AddObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __AddObject(soap, soap_tmp_cwmp__AddObject.ObjectName, soap_tmp_cwmp__AddObject.ParameterKey, &_param_8);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__AddObjectResponse(soap, &_param_8);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__AddObjectResponse(soap, &_param_8, "cwmp:AddObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__AddObjectResponse(soap, &_param_8, "cwmp:AddObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__AddObjectIPTV(struct soap *soap)
{	struct cwmp__AddObjectIPTV soap_tmp_cwmp__AddObjectIPTV;
	struct cwmp__AddObjectResponse _param_9;
	soap_default_cwmp__AddObjectResponse(soap, &_param_9);
	soap_default_cwmp__AddObjectIPTV(soap, &soap_tmp_cwmp__AddObjectIPTV);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__AddObjectIPTV(soap, &soap_tmp_cwmp__AddObjectIPTV, "cwmp:AddObjectIPTV", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __AddObjectIPTV(soap, soap_tmp_cwmp__AddObjectIPTV.ObjectName, soap_tmp_cwmp__AddObjectIPTV.ParameterKey, &_param_9);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__AddObjectResponse(soap, &_param_9);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__AddObjectResponse(soap, &_param_9, "cwmp:AddObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__AddObjectResponse(soap, &_param_9, "cwmp:AddObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__DeleteObject(struct soap *soap)
{	struct cwmp__DeleteObject soap_tmp_cwmp__DeleteObject;
	struct cwmp__DeleteObjectResponse _param_10;
	soap_default_cwmp__DeleteObjectResponse(soap, &_param_10);
	soap_default_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__DeleteObject(soap, &soap_tmp_cwmp__DeleteObject, "cwmp:DeleteObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __DeleteObject(soap, soap_tmp_cwmp__DeleteObject.ObjectName, soap_tmp_cwmp__DeleteObject.ParameterKey, &_param_10);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__DeleteObjectResponse(soap, &_param_10);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__DeleteObjectResponse(soap, &_param_10, "cwmp:DeleteObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__DeleteObjectResponse(soap, &_param_10, "cwmp:DeleteObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Reboot(struct soap *soap)
{
    struct sockmsg sockMsg;
    struct cwmp__Reboot soap_tmp_cwmp__Reboot;
	struct cwmp__RebootResponse _param_11;
	soap_default_cwmp__RebootResponse(soap, &_param_11);
	soap_default_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Reboot(soap, &soap_tmp_cwmp__Reboot, "cwmp:Reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __Reboot(soap, soap_tmp_cwmp__Reboot.CommandKey, &_param_11);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__RebootResponse(soap, &_param_11);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__RebootResponse(soap, &_param_11, "cwmp:RebootResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__RebootResponse(soap, &_param_11, "cwmp:RebootResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
   
    memset(&sockMsg, 0x00, sizeof(sockMsg));
    sprintf(sockMsg.msg, "%s", SyMethodTypeToStr(SY_REBOOT));
    sockMsg.len = strlen(sockMsg.msg);
    strcpy(sockMsg.user, "tr069");
    Send2CmdProcThd(&sockMsg);
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Download(struct soap *soap)
{	struct cwmp__Download soap_tmp_cwmp__Download;
	struct cwmp__DownloadResponse _param_12;

    gsyGlobalParmStru.SessionFlags = SY_STATE_DOWNLOAD_PENDING; //hitler

	soap_default_cwmp__DownloadResponse(soap, &_param_12);
	soap_default_cwmp__Download(soap, &soap_tmp_cwmp__Download);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Download(soap, &soap_tmp_cwmp__Download, "cwmp:Download", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __Download(soap, soap_tmp_cwmp__Download.CommandKey, soap_tmp_cwmp__Download.FileType, soap_tmp_cwmp__Download.URL, soap_tmp_cwmp__Download.Username, soap_tmp_cwmp__Download.Password, soap_tmp_cwmp__Download.FileSize, soap_tmp_cwmp__Download.TargetFileName, soap_tmp_cwmp__Download.DelaySeconds, soap_tmp_cwmp__Download.SuccessURL, soap_tmp_cwmp__Download.FailureURL, &_param_12);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__DownloadResponse(soap, &_param_12);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__DownloadResponse(soap, &_param_12, "cwmp:DownloadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__DownloadResponse(soap, &_param_12, "cwmp:DownloadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
    gsyGlobalParmStru.SessionFlags = SY_STATE_DOWNLOAD_FIRMWARE_COMPLETE;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__Upload(struct soap *soap)
{	struct cwmp__Upload soap_tmp_cwmp__Upload;
	struct cwmp__UploadResponse _param_13;
	soap_default_cwmp__UploadResponse(soap, &_param_13);
	soap_default_cwmp__Upload(soap, &soap_tmp_cwmp__Upload);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__Upload(soap, &soap_tmp_cwmp__Upload, "cwmp:Upload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __Upload(soap, soap_tmp_cwmp__Upload.CommandKey, soap_tmp_cwmp__Upload.FileType, soap_tmp_cwmp__Upload.URL, soap_tmp_cwmp__Upload.Username, soap_tmp_cwmp__Upload.Password, soap_tmp_cwmp__Upload.DelaySeconds, &_param_13);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__UploadResponse(soap, &_param_13);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__UploadResponse(soap, &_param_13, "cwmp:UploadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__UploadResponse(soap, &_param_13, "cwmp:UploadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
    
    gsyGlobalParmStru.SessionFlags = SY_STATE_UPLOAD_COMPLETE; //hitler
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__FactoryReset(struct soap *soap)
{
    struct sockmsg sockMsg;
    struct cwmp__FactoryReset soap_tmp_cwmp__FactoryReset;
	struct cwmp__FactoryResetResponse _param_14;
	soap_default_cwmp__FactoryResetResponse(soap, &_param_14);
	soap_default_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__FactoryReset(soap, &soap_tmp_cwmp__FactoryReset, "cwmp:FactoryReset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __FactoryReset(soap, soap_tmp_cwmp__FactoryReset._, &_param_14);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__FactoryResetResponse(soap, &_param_14);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__FactoryResetResponse(soap, &_param_14, "cwmp:FactoryResetResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__FactoryResetResponse(soap, &_param_14, "cwmp:FactoryResetResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
    
    memset(&sockMsg, 0x00, sizeof(sockMsg));
    sprintf(sockMsg.msg, "%s", SyMethodTypeToStr(SY_FACTORY_RESET));
    sockMsg.len = strlen(sockMsg.msg);   
    strcpy(sockMsg.user, "tr069");
    Send2CmdProcThd(&sockMsg);
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__ScheduleInform(struct soap *soap)
{	struct cwmp__ScheduleInform soap_tmp_cwmp__ScheduleInform;
	struct cwmp__ScheduleInformResponse _param_15;
	soap_default_cwmp__ScheduleInformResponse(soap, &_param_15);
	soap_default_cwmp__ScheduleInform(soap, &soap_tmp_cwmp__ScheduleInform);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__ScheduleInform(soap, &soap_tmp_cwmp__ScheduleInform, "cwmp:ScheduleInform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ScheduleInform(soap, soap_tmp_cwmp__ScheduleInform.DelaySeconds, soap_tmp_cwmp__ScheduleInform.CommandKey, &_param_15);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__ScheduleInformResponse(soap, &_param_15);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__ScheduleInformResponse(soap, &_param_15, "cwmp:ScheduleInformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__ScheduleInformResponse(soap, &_param_15, "cwmp:ScheduleInformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_cwmp__TransferComplete(struct soap *soap)
{	struct cwmp__TransferComplete soap_tmp_cwmp__TransferComplete;
	struct cwmp__TransferCompleteResponse _param_16;
	soap_default_cwmp__TransferCompleteResponse(soap, &_param_16);
	soap_default_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete);
	soap->encodingStyle = "";
	if (!soap_get_cwmp__TransferComplete(soap, &soap_tmp_cwmp__TransferComplete, "cwmp:TransferComplete", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __TransferComplete(soap, soap_tmp_cwmp__TransferComplete.CommandKey, soap_tmp_cwmp__TransferComplete.FaultStruct, soap_tmp_cwmp__TransferComplete.StartTime, soap_tmp_cwmp__TransferComplete.CompleteTime, &_param_16);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_cwmp__TransferCompleteResponse(soap, &_param_16);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_cwmp__TransferCompleteResponse(soap, &_param_16, "cwmp:TransferCompleteResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
     || soap_connect(soap, gsyAcsCpeParamStru.URL, NULL)
     //|| soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_cwmp__TransferCompleteResponse(soap, &_param_16, "cwmp:TransferCompleteResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	//return soap_closesock(soap);
	return SOAP_OK;
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
