#ifndef _UTIL_H
#define _UTIL_H

//#define ANDROID_TEST
#define XMLPATH "./xx.xml"

#ifdef ANDROID_TEST
#define DPrint(...) __android_log_print(ANDROID_LOG_VERBOSE,"TM",__VA_ARGS__)
#else
#define DPrint(...) printf(__VA_ARGS__)
#endif

struct sy_device_id{
	char manufacturer[65];
	char oui[7];
	char product_class[65];
	char serial_number[65];
};

typedef struct sy_msg{
	sy_type type;
	sy_method_type method_type;
} symsg_t;

typedef enum{
	SY_GET_RPC_METHODS,
	SY_GET_PARAMETER_VALUES,
	SY_SET_PARAMETER_VALUES,
	SY_MSG_FAULT,
} sy_method_type;

typedef enum{
	SY_MSG_REQUEST,
	SY_INFORM,
	SY_MSG_RESPONSE,
} sy_type;

#define EVCPE_VERSION "0.1"
#define EVCPE_SOAP_ENC_XMLNS "soap-enc"
#define EVCPE_SOAP_ENV_XMLNS "soap-env"
#define EVCPE_CWMP_XMLNS "cwmp"
#define EVCPE_ACS_TIMEOUT 60
#define EVCPE_CREQ_INTERVAL 10
#define EVCPE_XML_INDENT "    "

typedef enum{
/*Network*/
    IPTV_CONFIG_PARAM_CONNECT_TYPE = 1,             //网络连接方式
    IPTV_CONFIG_PARAM_DHCP_USER = 2,                //DHCP用户名
    IPTV_CONFIG_PARAM_DHCP_PASSWD = 3,              //DHCP密码
    IPTV_CONFIG_PARAM_PPPOE_USER = 4,               //PPPOE用户名
    IPTV_CONFIG_PARAM_PPPOE_PASSWD = 5,             //PPPOE密码
    IPTV_CONFIG_PARAM_IPADDR = 6,	                //IP地址
    IPTV_CONFIG_PARAM_MASK = 7,                     //子网掩码
    IPTV_CONFIG_PARAM_DEFGATEWAY = 8,               //默认网关
    IPTV_CONFIG_PARAM_DNSMAIN = 9,                  //DNS1
    IPTV_CONFIG_PARAM_DNSBAK = 10,                  //DNS2
    IPTV_CONFIG_PARAM_MAC = 21,                     //MAC地址

/*Time*/
    IPTV_CONFIG_PARAM_TIMEZONE = 22,                //时区 
    IPTV_CONFIG_PARAM_NTPMAIN = 23,                 //NTP地址1            
    IPTV_CONFIG_PARAM_NTPBAK = 24,                  //NTP地址2

/*Upgrade*/
    IPTV_CONFIG_PARAM_UPGRADE_URL = 25,             //升级地址      
    IPTV_CONFIG_PARAM_UPGRADE_USER = 26,            //升级服务器用户名     
    IPTV_CONFIG_PARAM_UPGRADE_PASSWD = 27,           //升级服务器密码
    IPTV_CONFIG_PARAM_STARTUPGRADE = 28,			//升级操作
    IPTV_CONFIG_PARAM_FORCEUPGRADE = 29, 			//强制升级
    IPTV_CONFIG_PARAM_UPGRADERESULT = 30,			//升级结果

/*Basic Info*/
    IPTV_CONFIG_PARAM_MANUFACTORY = 32,              //生产厂商
    IPTV_CONFIG_PARAM_SN = 33,                       //序列号
    IPTV_CONFIG_PARAM_STBID = 34,                    //STBID
    IPTV_CONFIG_PARAM_HARDWARE_VER = 35,             //硬件版本号
    IPTV_CONFIG_PARAM_SOFTWARE_VER = 36,             //软件版本号
    IPTV_CONFIG_PARAM_LANGUAGE = 37,                 //语言

/*TR069 Setting*/
    IPTV_CONFIG_PARAM_MANAGESERVER_URL = 38,         //网管认证地址     
    IPTV_CONFIG_PARAM_MANAGESERVER_USER = 39,        //网管用户名
    IPTV_CONFIG_PARAM_MANAGESERVER_PASSWD = 40,      //网管密码
    IPTV_CONFIG_PARAM_HEARTBEAT = 41,                //心跳开关
    IPTV_CONFIG_PARAM_HEARTBEAT_INTERVAL = 42,       //心跳周期
    IPTV_CONFIG_PARAM_CPEUSER = 43,                  //CPEUSER
    IPTV_CONFIG_PARAM_CPEPASSWD = 44,                //CPEPASSWD

/*Authentication*/
    IPTV_CONFIG_PARAM_AUTH_MAINURL = 45,             //业务主认证地址
    IPTV_CONFIG_PARAM_AUTH_BAKURL = 46,              //业务备认证地址
    IPTV_CONFIG_PARAM_IPTVUSER = 47,                 //业务用户名
    IPTV_CONFIG_PARAM_IPTVPASSWD = 48,	             //业务密码

/*STB Reboot*/
    IPTV_CONFIG_PARAM_REBOOT = 49,

/*Log Report*/
    IPTV_CONFIG_PARAM_LOGSERVERURL = 55, 		    //FTP address
    IPTV_CONFIG_PARAM_LOGSERVERUSER = 56,			//FTP username
    IPTV_CONFIG_PARAM_LOGSERVERPASSWD  = 57,		//FTP Password
    IPTV_CONFIG_PARAM_LOGDURATION = 58,				//log time
    IPTV_CONFIG_PARAM_LOGMSGORFILE = 59, 			//log or file
    IPTV_CONFIG_PARAM_IGMPINFO = 60, 				//IGMP info
    IPTV_CONFIG_PARAM_HTTPINFO = 61,
    IPTV_CONFIG_PARAM_RTSPINFO = 62,
    IPTV_CONFIG_PARAM_PKGTOTALONESEC = 63,			//PkgTotalOneSec
    IPTV_CONFIG_PARAM_BYTETOTALONESEC = 64,	
    IPTV_CONFIG_PARAM_PKGLOSTRATE = 65,
    IPTV_CONFIG_PARAM_AVARAGERATE = 66,	
    IPTV_CONFIG_PARAM_BUFFER = 67,	
    IPTV_CONFIG_PARAM_ERROR = 68,
    IPTV_CONFIG_PARAM_LOGSWITCH = 69,				//log upload switcher

/*Video performance parameters*/
    IPTV_CONFIG_PARAM_PKGLOSTR1 = 70,			    
    IPTV_CONFIG_PARAM_PKGLOSTR2,	
    IPTV_CONFIG_PARAM_PKGLOSTR3,			
    IPTV_CONFIG_PARAM_PKGLOSTR4,		
    IPTV_CONFIG_PARAM_PKGLOSTR5,			
    IPTV_CONFIG_PARAM_HDPKGLOSTR1 = 75,			
    IPTV_CONFIG_PARAM_HDPKGLOSTR2,		
    IPTV_CONFIG_PARAM_HDPKGLOSTR3,		
    IPTV_CONFIG_PARAM_HDPKGLOSTR4,		
    IPTV_CONFIG_PARAM_HDPKGLOSTR5,		
    IPTV_CONFIG_PARAM_BITRATER1 = 80,	
    IPTV_CONFIG_PARAM_BITRATER2,		
    IPTV_CONFIG_PARAM_BITRATER3,		
    IPTV_CONFIG_PARAM_BITRATER4,		
    IPTV_CONFIG_PARAM_BITRATER5,		
    IPTV_CONFIG_PARAM_HDBITRATER1 = 85,		
    IPTV_CONFIG_PARAM_HDBITRATER2,		
    IPTV_CONFIG_PARAM_HDBITRATER3,		
    IPTV_CONFIG_PARAM_HDBITRATER4,		
    IPTV_CONFIG_PARAM_HDBITRATER5,	

    IPTV_CONFIG_PARAM_SUPPORTPROTOCOLS = 90,        //StreamingControlProtocols
    IPTV_CONFIG_PARAM_TRANSPORTPROTOCOLS,           //StreamingTransportProtocols
    IPTV_CONFIG_PARAM_TRANSPORTCTLPROTOCOLS,	    //StreamingTransportControlProtocols
    IPTV_CONFIG_PARAM_PLEXTYPE,	                    //MultiplexTypes
    IPTV_CONFIG_PARAM_DEJITTERBUFFERSIZE,	        //MaxDejitteringBufferSize
    IPTV_CONFIG_AUDIOSTANDARDS,	                    //AudioStandards
    IPTV_CONFIG_PARAM_VIDEOSTANDARDS = 96,          //VideoStandards
    IPTV_CONFIG_PARAM_QOSSERVERURL = 97,            //QosServerUrl
    IPTV_CONFIG_PARAM_QOSUPLOADINTERVAL = 98,
    IPTV_CONFIG_PARAM_RECORDINTERVAL = 99,          //LogRecordInterval    
    IPTV_CONFIG_PARAM_MONITORINGINTERVAL = 100,     //MonitoringInterval
    IPTV_CONFIG_PARAM_VIDEOLOGINFO = 101,	        //视频性能日志文件
    IPTV_CONFIG_PARAM_DIAGNOSTICSSTATE,             //DiagnosticsState
    IPTV_CONFIG_PARAM_PLAYURL,                      //PlayURL
    IPTV_CONFIG_PARAM_PLAYSTATE,                    //PlayState
    
    IPTV_CONFIG_PARAM_STARTPOINT,
    IPTV_CONFIG_PARAM_ENDPOINT,
    IPTV_CONFIG_PARAM_AUTHNUBERS,
    IPTV_CONFIG_PARAM_AUTHFAILNMB,
    IPTV_CONFIG_PARAM_AUTHFAILINFO,
    IPTV_CONFIG_PARAM_MULTIREQNUM,
    IPTV_CONFIG_PARAM_MULTIRRT,
    IPTV_CONFIG_PARAM_MULTIFAILNMB,
    IPTV_CONFIG_PARAM_MULTIFAILNINFO,
    IPTV_CONFIG_PARAM_VODREQNMB,
    IPTV_CONFIG_PARAM_VODRRT,
    IPTV_CONFIG_PARAM_VODFAILNMB,
    IPTV_CONFIG_PARAM_VODFAILINFO,
    IPTV_CONFIG_PARAM_HTTPREQNMB,
    IPTV_CONFIG_PARAM_HTTPRRT,
    IPTV_CONFIG_PARAM_HTTPFAILNMB,
    IPTV_CONFIG_PARAM_HTTPFAILINFO,
    IPTV_CONFIG_PARAM_MULTIABENDNMB,
    IPTV_CONFIG_PARAM_VODABENDNMB,
    IPTV_CONFIG_PARAM_MULTIABENDUPNMB,
    IPTV_CONFIG_PARAM_VODABENDUPNMB,
    IPTV_CONFIG_PARAM_HD_MULTIABENNMB,
    IPTV_CONFIG_PARAM_HD_VODABENDNMB,
    IPTV_CONFIG_PARAM_HD_MULTIABENUPNMB,
    IPTV_CONFIG_PARAM_HD_VODABENDUPNMB,
    IPTV_CONFIG_PARAM_PLAYERRORNMB,
    IPTV_CONFIG_PARAM_PLAYERRORINFO,
    IPTV_CONFIG_PARAM_MULTIPACKETSLOSTR1NMB,
    IPTV_CONFIG_PARAM_MULTIPACKETSLOSTR2NMB,
    IPTV_CONFIG_PARAM_MULTIPACKETSLOSTR3NMB,
    IPTV_CONFIG_PARAM_MULTIPACKETSLOSTR4NMB,
    IPTV_CONFIG_PARAM_MULTIPACKETSLOSTR5NMB,
    IPTV_CONFIG_PARAM_FECMULTIPACKETSLOSTR1NMB,
    IPTV_CONFIG_PARAM_FECMULTIPACKETSLOSTR2NMB,
    IPTV_CONFIG_PARAM_FECMULTIPACKETSLOSTR3NMB,
    IPTV_CONFIG_PARAM_FECMULTIPACKETSLOSTR4NMB,
    IPTV_CONFIG_PARAM_FECMULTIPACKETSLOSTR5NMB,
    IPTV_CONFIG_PARAM_VODPACKETSLOSTR1NMB,
    IPTV_CONFIG_PARAM_VODPACKETSLOSTR2NMB,
    IPTV_CONFIG_PARAM_VODPACKETSLOSTR3NMB,
    IPTV_CONFIG_PARAM_VODPACKETSLOSTR4NMB,
    IPTV_CONFIG_PARAM_VODPACKETSLOSTR5NMB,
    IPTV_CONFIG_PARAM_ARQVODPACKETSLOSTR1NMB,
    IPTV_CONFIG_PARAM_ARQVODPACKETSLOSTR2NMB,
    IPTV_CONFIG_PARAM_ARQVODPACKETSLOSTR3NMB,
    IPTV_CONFIG_PARAM_ARQVODPACKETSLOSTR4NMB,
    IPTV_CONFIG_PARAM_ARQVODPACKETSLOSTR5NMB,
    IPTV_CONFIG_PARAM_MULTIBITRATER1NMB,
    IPTV_CONFIG_PARAM_MULTIBITRATER2NMB,
    IPTV_CONFIG_PARAM_MULTIBITRATER3NMB,
    IPTV_CONFIG_PARAM_MULTIBITRATER4NMB,
    IPTV_CONFIG_PARAM_MULTIBITRATER5NMB,
    IPTV_CONFIG_PARAM_VODBITRATER1NMB,
    IPTV_CONFIG_PARAM_VODBITRATER2NMB,
    IPTV_CONFIG_PARAM_VODBITRATER3NMB,
    IPTV_CONFIG_PARAM_VODBITRATER4NMB,
    IPTV_CONFIG_PARAM_VODBITRATER5NMB,
    IPTV_CONFIG_PARAM_HD_MULTIPACKETSLOSGR1NMB,
    IPTV_CONFIG_PARAM_HD_MULTIPACKETSLOSGR2NMB,
    IPTV_CONFIG_PARAM_HD_MULTIPACKETSLOSGR3NMB,
    IPTV_CONFIG_PARAM_HD_MULTIPACKETSLOSGR4NMB,
    IPTV_CONFIG_PARAM_HD_MULTIPACKETSLOSGR5NMB,
    IPTV_CONFIG_PARAM_HD_FECMULTIPACKETSLOSGR1NMB,
    IPTV_CONFIG_PARAM_HD_FECMULTIPACKETSLOSGR2NMB,
    IPTV_CONFIG_PARAM_HD_FECMULTIPACKETSLOSGR3NMB,
    IPTV_CONFIG_PARAM_HD_FECMULTIPACKETSLOSGR4NMB,
    IPTV_CONFIG_PARAM_HD_FECMULTIPACKETSLOSGR5NMB,
    IPTV_CONFIG_PARAM__HD_VODPACKETSLOSGR1NMB,
    IPTV_CONFIG_PARAM__HD_VODPACKETSLOSGR2NMB,
    IPTV_CONFIG_PARAM__HD_VODPACKETSLOSGR3NMB,
    IPTV_CONFIG_PARAM__HD_VODPACKETSLOSGR4NMB,
    IPTV_CONFIG_PARAM__HD_VODPACKETSLOSGR5NMB,
    
    IPTV_CONFIG_PARAM__HD_ARQVODPACKETSLOSTR1NMB,
    IPTV_CONFIG_PARAM__HD_ARQVODPACKETSLOSTR2NMB,
    IPTV_CONFIG_PARAM__HD_ARQVODPACKETSLOSTR3NMB,
    IPTV_CONFIG_PARAM__HD_ARQVODPACKETSLOSTR4NMB,
    IPTV_CONFIG_PARAM__HD_ARQVODPACKETSLOSTR5NMB,
    IPTV_CONFIG_PARAM__HD_MULTIBITRATER1NMB,
    IPTV_CONFIG_PARAM__HD_MULTIBITRATER2NMB,
    IPTV_CONFIG_PARAM__HD_MULTIBITRATER3NMB,
    IPTV_CONFIG_PARAM__HD_MULTIBITRATER4NMB,
    IPTV_CONFIG_PARAM__HD_MULTIBITRATER5NMB,
    IPTV_CONFIG_PARAM__HD_VODBITRATER1NMB,
    IPTV_CONFIG_PARAM__HD_VODBITRATER2NMB,
    IPTV_CONFIG_PARAM__HD_VODBITRATER3NMB,
    IPTV_CONFIG_PARAM__HD_VODBITRATER4NMB,
    IPTV_CONFIG_PARAM__HD_VODBITRATER5NMB,

    IPTV_CONFIG_PARAM_BUFINCNMB,
    IPTV_CONFIG_PARAM_BUFDECNMB,
    IPTV_CONFIG_PARAM_FRAMELOSTR1NMB,
    IPTV_CONFIG_PARAM_FRAMELOSTR2NMB,
    IPTV_CONFIG_PARAM_FRAMELOSTR3NMB,
    IPTV_CONFIG_PARAM_FRAMELOSTR4NMB,
    IPTV_CONFIG_PARAM_FRAMELOSTR5NMB,

    
    IPTV_CONFIG_PARAM_CHANGED = 501,
    IPTV_CONFIG_PARAM_SCREENOFF	= 502,
    IPTV_CONFIG_PARAM_RESTOREFACTORY = 503,
    IPTV_CONFIG_PARAM_FULLSCREENSTATE=504,
    IPTV_CONFIG_PARAM_SWITCHCHANNEL=506,
    IPTV_CONFIG_PARAM_WORKTIME=507,
    IPTV_CONFIG_PARAM_REALBITRATE=508,
    IPTV_CONFIG_PARAM_ORIGINBITRATE=509,
    IPTV_CONFIG_PARAM_FINALFAILAUTHURL=510,
    IPTV_CONFIG_PARAM_GETORSETDATA = 1001,
    IPTV_CONFIG_PARAM_JNIDETACH = 1002,
} iptv_config_param;

#endif

